<?php
$activePage = "Pathfinder";
$loggedUser = true;
$user = 'Ettowak';
$valide = array('jpg', 'png', 'webp');
//tableau pour testé le carrousel
$adventuresContent = ['Titre'=>'<h2>Legacy of Dragons</h2>', 'Chapitre 1 <br> La légende débute.' => 'Odio eos, aspernatur modi vero omnis error quisquam? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Necessitatibus, dignissimos reprehenderit quas, nulla commodi neque suscipit, recusandae ratione temporibus ab reiciendis sit? Odio eos, aspernatur modi vero omnis error quisquam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur saepe tenetur cupiditate placeat dolorum a deserunt deleniti. Facilis nostrum saepe praesentium veritatis quos excepturi alias, tempora debitis unde animi necessitatibus!','illustration1' => 'secretCavern.jpg', 'Chapitre 2 <br> Une légende rapide.'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos laborum possimus beatae distinctio necessitatibus architecto repellat quam quos vero doloribus consequatur sequi voluptate fugiat, culpa a dolores accusantium, hic veniam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos laborum possimus beatae distinctio necessitatibus architecto repellat quam quos vero doloribus consequatur sequi voluptate fugiat, culpa a dolores accusantium, hic veniam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos laborum possimus beatae distinctio necessitatibus architecto repellat quam quos vero doloribus consequatur sequi voluptate fugiat, culpa a dolores accusantium, hic veniam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos laborum possimus beatae distinctio necessitatibus architecto repellat quam quos vero doloribus consequatur sequi voluptate fugiat, culpa a dolores accusantium, hic veniam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos laborum possimus beatae distinctio necessitatibus architecto repellat quam quos vero doloribus consequatur sequi voluptate fugiat, culpa a dolores accusantium, hic veniam!' ];
$characters = ['perso1' => ['firstname' => 'Shagaroth', 'lastname' => 'Grumma', 'race' => 'Orc', 'age' => '32', 'profilImg' => 'd478d52a786cb2d5b4ee55577efdf08f','job'=>'Mineur', 'destiny'=>'3', 'courage'=>'12', 'intell'=>'5', 'charisma'=>'4','strenght'=>'8', 'agility'=>'1','attack'=>'15', 'defense'=>'4'], 'perso2' => ['firstname' => 'Shagaroth', 'lastname' => 'Grumma', 'race' => 'Orc', 'age' => '32', 'profilImg' => 'd478d52a786cb2d5b4ee55577efdf08f','job'=>'Alchimiste', 'destiny'=>'3','courage'=>'5','intell'=>'8', 'charisma'=>'1','strenght'=>'8', 'agility'=>'1','attack'=>'12', 'defense'=>'10']];
include 'Includes/header.php';
?>